# Generated by Django 2.2.4 on 2019-08-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(help_text='Enter your name', max_length=30)),
                ('mobile_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(help_text='Enter password', max_length=256)),
            ],
        ),
    ]
