# Generated by Django 2.2.4 on 2019-08-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_x'),
    ]

    operations = [
        migrations.DeleteModel(
            name='X',
        ),
    ]
