# Generated by Django 2.2.5 on 2019-09-17 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_auto_20190917_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='y',
            name='x_link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link_to_x', to='sample.X'),
        ),
    ]
